// jest-puppeteer.config.js
module.exports = {
  launch: {
    headless: true,
    ignoreHTTPSErrors: true,
    slowMo: 50,
    args: [
      '--disable-background-networking',
      '--disable-background-timer-throttling',
      '--disable-breakpad',
      '--disable-client-side-phishing-detection',
      '--disable-default-apps',
      '--disable-dev-shm-usage',
      '--disable-extensions',
      '--disable-features=site-per-process',
      '--disable-hang-monitor',
      '--disable-popup-blocking',
      '--disable-prompt-on-repost',
      '--disable-sync',
      '--disable-translate',
      '--metrics-recording-only',
      '--no-first-run',
      '--safebrowsing-disable-auto-update',
      '--enable-automation',
      '--password-store=basic',
      '--use-mock-keychain',
      '--headless',
      '--hide-scrollbars',
      '--no-sandbox',
      '--font-render-hinting=none',
      '--ignore-certificate-errors',
    ],
  },
  server: {
    command: 'yarn start',
    port: 3000,
  },
};
